#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAA...

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/<token>
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$public_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379
    listen-peer-urls: http://0.0.0.0:2380
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
      
write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp
      PermitRootLogin no
      AllowUsers core
      PasswordAuthentication no
      ChallengeResponseAuthentication no
  - path: /srv/logstash/config
    permissions: '0755'
    content: |
      input {
        tcp {
          port => 6666
          tags => ["tcp"]
          type => tcpData
        }
      }
      filter {
      }
      output {
        stdout {}
        elasticsearch {
          host => "elasticsearch"
          protocol => "http"
        }
      }